- .travis.yml
- static/.github/PULL_REQUEST_TEMPLATE.md
- static/README.md
travis: use custom FQDN for GitHub pages: https://docs.egi.eu
Before one hour the Let's Encrypt certificate for HTTPS should be setup.
> travis: use custom FQDN for GitHub pages

- .travis.yml
- README.md
- config.toml
Switch to docsy theme: disable building errors to at least allow to publish the latest version.
> Switch to docsy theme: disable building errors

- CODEOWNERS
- content/en/users/training/infrastructure/_index.md
Training infra: fix a typo, a link and enforce style (that, if you ask, was automatically formatted by vim when saving changes).
> Training infra: fix a typo, a link and enforce style.

- config.toml
config: use lunar.js search instead of non working google search as documented on https://www.docsy.dev/docs/adding-content/navigation/#configure-local-search-with-lunr.
Fix #46
> config: use lunar.js search instead of non working google search

- content/en/providers/getting-started/_index.md
Some simple text to remove a placeholder.
Wondering if notebooks doc shouldn't go under internal services, is it really something to be deployed by service providers themselves?
> getting started providers: route to various places

- content/en/users/check-in/linking/_index.md
This PR fixes the missing table of content in the [linking guide](https://docs.egi.eu/users/check-in/linking/).
If there is defined only one header in the body of the guide, then the table of contents is hidden.
Also to maintain the guide clean, there is a commit for fixing the code styling
> Check in add header to linking guide

- content/en/providers/check-in/sp/_index.md
This PR adds the description of the new SSH Public Key attribute in Service Provider guide of Check-in
> [Check-in] Add description for SSH Public Key attribute

- content/en/providers/check-in/sp/_index.md
This PR removes the deprecated scope `refeds_edu` and replaces the old claim name `edu_person_entitlements` with `eduperson_entitlement`
> Hotfix replace edu person entiltements

- .github/workflows/deploy.yml
- README.md
- config.toml
- content/en/_index.md
- content/en/about/contributing/_index.md
- content/en/about/contributing/git/_index.md
- content/en/about/contributing/style/_index.md
- content/en/providers/cloud-compute/openstack/_index.md
- content/en/providers/notebooks/architecture/_index.md
- content/en/users/cloud-compute/auth/_index.md
- content/en/users/cloud-compute/federation/_index.md
- content/en/users/cloud-compute/vmi/_index.md
- content/en/users/cloud-container-compute/k8s.md
- content/en/users/notebooks/faq/_index.md
- content/en/users/notebooks/kernels/_index.md
- content/en/users/notebooks/training/_index.md
- static/README.md
Update references to EGI-Foundation, and use EGI-Federation as the GitHub organisation has been renamed.
> Update references to EGI-Foundation, and use EGI-Federation

- .github/workflows/lint.yml
Full git history is needed to get a proper list of changed files within `super-linter`.
As documented on https://github.com/github/super-linter#example-connecting-github-action-workflow
Should address issues with super-linter not able to find all the changes.
> Full git history needed for proper list of changed files

- content/en/about/concepts/_index.md
Update link to EGI glossary, using the shortlink via go.egi.eu
> Update link to EGI glossary

- content/en/providers/check-in/sp/_index.md
This PR extends the "user attributes" section adding description for GOCDB roles in Service Provider guide of Check-in.
> Description for GOCDB roles

- config.toml
This should fix issues with editing from the web, default branch is hardcoded on `master` and we moved to `main`.
> config.toml: we moved to main

- content/en/users/notebooks/_index.md
Update documentation due to EGI Notebooks plan to have limited authorization for the users to vo.notebooks.egi.eu only.
(It can be used as is, but feel free to reword or enhance it as I'm not much writer.)
https://jira.egi.eu/browse/IMSCHM-58
> EGI notebooks authorizaton will be limited to vo.notebooks.egi.eu

- .github/workflows/deploy.yml
Do not run deploy step for forks, fixing #277.
Not tested, but done according to https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif and https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context.
> Do not run deploy step for forks, fixing #277.

- .github/workflows/preview_pr.yml
Add workflow trying to deploy to alternate repo from a PR.
* For security reasons only PR having the label `preview` added to them will be build and deploy for preview. See https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels, only people having at least triage access can apply/dismiss labels
* The deploy is done to an alternate repository: https://github.com/EGI-Federation/documentation-preview/
* The rendering should be available at http://docs.egi.eu/documentation-preview/{PR}
Fix #173.
> Add workflow trying to deploy to alternate repo from a PR

- .github/workflows/preview_pr.yml
Deploy preview to local repository, as it's not easily possible to access a token or secret allowing to push to a remote repository from a PR.
See https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow.
> preview_pr: deploy preview to local repository

- .github/linters/.markdownlint.json
markdownlint: disable line-length and command-show-output as previously discussed.
* [line-length](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length)
* [command-show-output](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014)
Discussed in #271 and #272.
> markdownlint: disable line-length and command-show-output as previously discussed.

- .github/linters/.markdownlint.json
Try to find syntax for configuring MD013 exceptions, see https://github.com/EGI-Federation/documentation/pull/317/checks?check_run_id=3536232892#step:4:103 from #317.
This PR should set a max line length of 120 to be more comfortable, with line length checks disabled for code excerpts and tables that are the legit cases for longer lines.
See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013
> Try to find syntax for configuring MD013 exceptions

- content/en/users/tutorials/data-transfer-grid-storage/_index.md
Remove the RSA key markers to lazily address errors reports by gitleaks, see https://github.com/EGI-Federation/documentation/pull/333/checks?check_run_id=3755392770#step:4:1064
https://github.com/zricethezav/gitleaks
It's desirable to keep gitleaks running and showing the PRIVATE KEY tags doesn't seem to be that required/useful.
> Remove the RSA key markers to lazily address errors reports by gitleaks

- content/en/providers/check-in/sp/_index.md
The userinfo endpoint for the production MasterPortal pointed to the aai-demo OIDC provider instead (copy&paste error probably)
> Fix userinfo endpoint production MasterPortal

- content/en/internal/collaboration-tools/_index.md
- content/en/internal/collaboration-tools/mailing-lists/_index.md
- content/en/internal/collaboration-tools/service-information/_index.md
* Include a page about Collaboration Tools moved from https://wiki.egi.eu/wiki/EGI_Collaboration_tools
* Include a page about mailman moved from https://wiki.egi.eu/wiki/Mailing_list_administration
> Move initial documentation for Collaboration Tools

- content/en/providers/check-in/sp/_index.md
Ignore textlint due to ORCID iD error.
Fixing error introduced by #424 and still reported in #425.
> Ignore textlint due to ORCID iD error

- content/en/providers/check-in/sp/_index.md
It was highlighted that there is a need to clarify and insist on the fact that authorisation should be put in place by service providers to avoid  potential abuse of their service due to the lack of access control.
This PR aims a providing a first quick step into that direction.
Changes:
* Highlight the need to put authorisation in place to avoid service abuse.
* Move the important URLs from the integration workflow to the section on General Information where it seems more logical to be.
> Highlight the need to put authorisation in place to avoid service abuse

- content/en/internal/collaboration-tools/_index.md
- content/en/internal/collaboration-tools/certificates/_index.md
Document certificate software provisioning for central services. I've documented this under the Collaboration Tools internal service, the SDTP is being updated and discussions are still to take place on the exact list of components. But until know, we can keep it here, unless anyone is having a better suggestion.
Documentation status:
> Document certificate provisioning

- content/en/users/aai/check-in/vos/_index.md
Please correct me if I am wrong but the following sentence is confusing in https://docs.egi.eu/users/aai/check-in/vos/#managing-cou-admin-members:
> COU Admin role is granted to a CO Person
Example of roles are `vm_operator` or `member`, so rather than using `COU Admin` role I think it is better to say `COU Admin Group` membership.
What do you think?
---
> COU admin role vs membership

- content/en/providers/check-in/sp/_index.md
- content/en/users/aai/check-in/obtaining-tokens/oidc-agent/_index.md
- content/en/users/aai/check-in/obtaining-tokens/token-portal/_index.md
This PR introduce the following changes:
- Add a section for the OP migration in the end-user guide
- Add note for the minimum required version of oidc-agent
> [Check-in] Add OP migration section in the end-user guide

- content/en/providers/check-in/sp/_index.md
This PR adds the `client_secret` parameter to the examples of the Device Authorization Requests.
> [Check-in] Add `client_secret` to Device Authorization Request

- content/en/internal/guidelines-software-development/_index.md
software dev guidelines: mention MS OSS SSC framework, a good read on how to manage OSS dependencies.
> software dev guidelines: mention MS OSS SSC framework

- .github/workflows/build.yml
- .github/workflows/build_pr_preview.yml
- .github/workflows/check-links.yml
- .github/workflows/delete_pr_preview.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
Update to node 16, as node 12 is no more supported since April 2022.
Node 16 is the current LTS, supported till 2023-09-11.
Bump actions relying on node 12 to latest version.
References:
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ 
- https://github.com/nodejs/release#release-schedule
- https://github.com/actions/checkout/releases/tag/v3.0.0
> Update to node 16

- .github/dependabot.yml
Import dependabot.yml.
See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions
> Import dependabot.yml, apparently dependabot wasn't running for this repo.

- .github/workflows/deploy_pr_preview.yml
GitHub actions: use updated octokit call.
This should fix issues with deploying pull request previews, as identified in #526 .
Tested in https://github.com/gwarf/documentation/actions/runs/3312681659/jobs/5469654742
> GitHub actions: use updated octokit call

- content/en/providers/check-in/sp/_index.md
This PR removes the MITREid Connect references and endpoints from the SP guide.
This PR should be merged on Friday 21 October and beyond, when the MITREid Connect based OP will be decommissioned.
> [Check-in] Remove references to MITREid Connect from SP guide

- content/en/users/compute/orchestration/workload-manager/_index.md
- content/en/users/dev-env/notebooks/integration/_index.md
Information added on the access to DIRAC client via CVMFS to document DIRAC-Notebook integration. 
Changes in : 
- `content/en/users/compute/orchestration/workload-manager/_index.md`: added CVMFS information, changed the header level for **Technical Support** paragraph
- `content/en/users/dev-env/notebooks/integration/_index.md`: added CVMFS information
---
Answers JIRA ticket https://jira.egi.eu/browse/ACETA-142
> Documentation on using DIRC CLI via CVMFS

- content/en/providers/check-in/sp/_index.md
This PR introduces the following changes:
- Add section for Logout Endpoint
- Fix case of OIDC terminology
- Update instruction of creating SAML SP metadata
- Add section for Redirect URIs
- Add section for UserInfo Endpoint
- Add section for Introspection Endpoint
- Fix notes refering to the endpoints table
- Move flow descriptions from `Endpoints` to `Grant Types` section
- Make duplicate headers unique in order to use them in links
> [Check-in] Add section for the Logout Endpoint

- CODEOWNERS
CODEOWNERS: remove Catalin, as discussed with him.
Some people are configured as code owners but are not able to follow with the reviews, it's cleaner to remove them than having to force the merge.
Let me know if you think of other adjustments to do.
This should also unblock #535.
Close #68.
Close #105.
> CODEOWNERS: remove Catalin, as discussed with him

- content/en/users/compute/cloud-compute/auth/_index.md
- content/en/users/compute/orchestration/ec3/developers/_index.md
- content/en/users/data/storage/block-storage/_index.md
- content/en/users/data/storage/object-storage/_index.md
- content/en/users/getting-started/cli/_index.md
- content/en/users/getting-started/task-force/_index.md
- content/en/users/training/_index.md
The FedCloud CLI was using an env var EGI_SITE to set the site on which to operate. This is not working since a while now, because of a bug in a Python lib. Details at https://github.com/tdviet/fedcloudclient/issues/150. 
Thus I removed this from our user docs, will update when a workaround is implemented in a new version of FedCloud CLI.
> Remove fedcloudcli env var EGI_SITE

- .github/workflows/check-links.yml
- .github/workflows/lint.yml
- .github/workflows/spelling.yml
Lint and spell only changed files to limit wast of resources..
The codebase should already be in a sane situation, lint and spell checks have been running across all the codebase.
> Lint and spell only changed files to limit wast of resources.

- .github/linters/.ecrc
Prevent editorcondig-checker to look in markdown files as it triggers too many false positives, cf #593 .
> Prevent editorcondig-checker to look in markdown files

- content/en/providers/check-in/sp/_index.md
This pull request removes the alert that warns users about the upcoming migration to Keycloak. The migration process has already been successfully executed, and this alert is no longer needed. By removing it, we ensure a streamlined user experience without unnecessary warnings to service owners/developers.
> Remove note about Keycloak migration from OIDC guide

- .github/actions/spelling/allow.txt
- .github/actions/spelling/patterns.txt
- content/en/users/tutorials/advanced/_index.md
- content/en/users/tutorials/intermediate/_index.md
- content/en/users/tutorials/scientific/_index.md
> Add new tutorials

- .github/actions/spelling/allow.txt
- .github/actions/spelling/expect.txt
- .github/workflows/spelling.yml
Update check-spelling configuration to address errors in checks done in PRs.
> Update check-spelling configuration

- .github/linters/.yaml-lint.yml
- .github/workflows/deploy_pr_preview.yml
Fix some lint-reported errors on GitHub actions.
By default yamllint will check keys for truthy: reporting useless errors, like for GitHub actions: https://yamllint.readthedocs.io/en/stable/rules.html#module-yam
llint.rules.truthy
> Fix lint-reported errors on GitHub actions

- content/en/providers/cloud-compute/openstack/vo_config.md
Document the use of the `VO` property so discovery can properly work with cloud-info-provider
---
> Add information about the VO property

- content/en/internal/operations-portal/_index.md
Drop legacy link to wiki.egi.eu, and point to the wiki at IN2P3.
> Update external link to operations portal documentation

- .github/actions/spelling/allow.txt
- content/en/providers/cloud-compute/openstack/aai.md
Configuration to enable permissions for EGI.eu staff to execute `openstack user list`.
This will allow EGI.eu staff to proactively notify creators of long-running VMs and free up resources accordingly.
Many thanks @astalosj and @enolfc for your help!
---
> Adding config for identity:list_users

- content/en/providers/cloud-compute/openstack/aai.md
Thanks @astalosj for spotting the mistake. It should be fixed now.
---
> Revert openstack commands for the ops VO in keystone federation support

- content/en/providers/check-in/sp/_index.md
This pull request aims to improve the integration documentation for EGI Check-in. The changes include providing additional clarity regarding the purpose and differences of the development environment compared to the demo and production environments. 
A note has been added to highlight that the development environment is intended for testing the latest features and may differ from demo/prod in terms of stability and functionality. These changes aim to improve the understanding of the integration process and help users make informed decisions about the integration environment when testing their Service Providers.
> Improve Check-in service integration guide

- content/en/users/data/management/datahub/_index.md
> Add quota for playground space on EGI Datahub

- content/en/users/dev-env/replay/_index.md
Just adding the quota for the service
---
> Add quota for Replay service

- content/en/users/tutorials/adhoc/oidc-agent-fedcloudclient-terraform/_index.md
> Fix deprecated URL

- content/en/internal/configuration-database/scopes/_index.md
This PR will add documentation for GreenDIGIT Reserved Tag to the configuration database's documentation.
Related GGUS ticket: https://ggus.eu/index.php?mode=ticket_info&ticket_id=167895
> Add documentation for GreenDIGIT Reserved Tag

- content/en/users/compute/orchestration/im/cli/_index.md
Port 31443 does not work any more and it has been replaced by 443. The documentation has been changed accordingly
> Replace port number 31443

- .github/actions/spelling/expect.txt
- content/en/providers/cloud-compute/openstack/_index.md
- content/en/users/compute/orchestration/im/_index.md
- content/en/users/compute/orchestration/im/cli/_index.md
> Update URLs for IM

- content/en/internal/configuration-database/scopes/_index.md
Remove references to REBUS in favour of reference to CRIC - as REBUS is outdated and CRIC should be used.
> Update WLCG scope tag procedure

- content/en/users/compute/software-distribution/_index.md
* small language correction
* add repository omnibenchmark to the list
---
> Update CVMFS documentation

- .github/workflows/lint.yml
gitleaks got disabled in #511, this PR is meant to re-enable and test if the configuration file is finally taken into account.
Fix #516
> Re-enable gitleaks

- .github/workflows/build_pr_preview.yml
Try to make the build preview work again
---
**Related issue :** #685
> Give permissions to write

- .github/workflows/deploy_pr_preview.yml
The actions should only be triggered when a label is set, and only selected users can set labels.
As per https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests, `contents: write` should be required to push the content to the preview branch, and `pull-requests: write` should be required for writing the comment.
> Add required permissisons to deploy previews

- .github/workflows/build_pr_preview.yml
- .github/workflows/delete_pr_preview.yml
I think the deletion of PR preview never works, let's see if we can get it working.
> chore: adjust delete PR workflow name and set required permissions

- .github/workflows/delete_pr_preview.yml
The proper branch is checked out by the checkout action
> chore: remove useless parameter for EndBug/add-and-commit

- .github/workflows/mega-linter.yml
- .github/workflows/spelling.yml
There is no real need to spend cycles doing a spell check when pushing to main, especially if there won't be follow up on failures.
> chore: disable spell check workflow on push, only use it in PR

- .github/workflows/delete_pr_preview.yml
Uses [pull_request_target](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target) to delete previews of PRs from forks.
See also https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
It grants write access using the GITHUB_TOKEN, but it is safe as:
- No code from the PR is built or executed
- The workflow file in use is the one from the base branch (main)
Fix #696
> chore: use pull_request_target to allow deleting previews from froks

- .github/workflows/deploy.yml
Since some time I was wondering why no docs.egi.eu pages are present in Google search. I just made some verifications and just realised that until now the indexing by search engines is disabled due the presence of a meta tag in the source of the pages.
The [docsy theme](https://www.docsy.dev/) version we use relies on having a `HUGO_ENV` variable set: https://github.com/google/docsy/blob/f85c845226f30a4b2a55085d142e96def89e4c3f/layouts/partials/head.html#L10-L14
For the record a commit, added after the version we use changes this behaviour, thus this may have to be revised when updating the theme: https://github.com/google/docsy/commit/7e2e9298db9aa5866813e9ed17454b39aca81798
> chore: ensure build is considered production to enable indexing

- content/en/providers/operations-manuals/operations-start-guide/_index.md
The GGUS documentation, at least with regards to registration, seems out of date. This PR updates the documentation with the current process (or at least my understanding of it) for accessing / registering as a support in the new GGUS system.
> Update GGUS section following launch of new GGUS

- .github/actions/spelling/allow.txt
- content/en/internal/configuration-database/scopes/_index.md
This PR updates the configuration database documentation around reserved scopes, specifically:
- adding a note that sites can (and should) remove reserved scope tags when they cease to be relevant
- fix link to old EGI wiki
> configuration-database: Removing scope tags

- content/en/internal/configuration-database/access/_index.md
the new link is: https://aai.egi.eu/auth/realms/id/account/#/enroll?groupPath=/goc.egi.eu
> new link to register to the GOCDB group in Check-in

- .cspell.yml
This adds the existing "allow.txt" list of words to the cspell configuration.
Note: there are two files configured for custom dictionaries (`allow.txt` and `expect.txt`)
These are a holdover from a time when the check-spelling action was used, this configuration is specific to that action. However since we cannot include the action in the pre-commit hooks, it was removed in favour of cspell.
**The word list configuration should be migrated to Cspell's.**
This will be done in a subsequent PR, but this should unblock people needing cspell to pass in pre-commit hooks.
> chore: add allowed words dictionary to cspell

- .cspell.yml
- .github/workflows/deploy_pr_preview.yml
- .github/workflows/link-health-check.yml
We are using CSpell to spell check the content.
It is reasonable to disable spell checking for markdown codeblocks, since maintaining words in these fenced blocks will create a lot of toil.
This adds a configuration to cspell to ignore codeblocks.
> chore: ignore markdown codeblocks in spelling

- .github/workflows/deploy_pr_preview.yml
- .github/workflows/link-health-check.yml
Update actions to include the root (`/`) of an area as well as the sub-pages
---
**Related issue :** #744
> ci(links): check the root of the area as well as sub-pages

- .github/workflows/deploy_pr_preview.yml
A spurious set of spaces was introduced to the deploy preview job.
---
**Related issue :** #751
> ci: remove spurious spaces in variable.

- .lycheeignore
Closed #755
Fix the `.lycheeignore` for urls with "+"
---
**Related issue :** #755
> chore: fix regexp escape for lychee ignore url line

- content/en/users/security/secrets-store/cli/_index.md
Update `VAULT_HOME` to fix the path to the secrets.
I also had issues due to the fact that my `egi` account in my `oidc-agent` was not having the `voperson_id` scope, thus the `jq` call was not returning it.
The `voperson_id` scope is not mentioned in the upstream `oidc-agent` configuration for the EGI provider at https://indigo-dc.gitbook.io/oidc-agent/user/oidc-gen/provider/egi, that is linked from https://docs.egi.eu/users/getting-started/cli/#authentication.
And https://docs.egi.eu/users/aai/check-in/obtaining-tokens/oidc-agent/ is not mentioning it too.
> fix: add missing /users/ path in the vault HOME
