.travis.yml
Import basic `.travis.yml` to fix #4.
=> Import basic .travis.yml

README.md
Document submodule and theme update
=> README: document submodule and theme update

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, AUTHORS, COPYRIGHT, LICENSE
Add COPYRIGHT, AUTHORS and github files for good citizenship.
Fix #3.
=> Add COPYRIGHT, AUTHORS and github files for good citizenship

.travis.yml, README.md
Travis should not clone public submodule, the directory will be used to build a new version.
=> Travis should not clone submodules

config.toml
Clean `config.toml` and update menu.
=> Clean config.toml and update menu.

config.toml, content/_index.md
Add a warning that doc are a non official work in progress.
=> Docs are not yet production ready

themes/hugo-theme-docdock-master/layouts/shortcodes/notice.html
Fix display of shortcodes. See https://github.com/vjeantet/hugo-theme-docdock/issues/193
=> Fix display of shortcodes. See https://github.com/vjeantet/hugo-theme-docdock/issues/193

config.toml
Collapse section menu: https://www.docsy.dev/docs/adding-content/navigation/#section-menu
=> Collapse section menu

content/providers/FedCloud/_index.md, content/users/FedCloud/gpgpu/_index.md, content/users/FedCloud/storage/_index.md
No need to include EGI every time
----
=> Remove some redundant EGI

content/operations/Getting started/_index.md
Forgotten commit for the previous PR :/
=> operations: clean getting started page

assets/icons/logo.svg, content/users/datahub/api/_index.md, content/users/datahub/clients/_index.md, content/users/datahub/links/_index.md
datahub: fix some links and cosmetics.
=> datahub: fix some links and cosmetics.

content/providers/notebooks/architecture/_index.md, content/providers/notebooks/operations/_index.md, content/users/fedcloud/auth/_index.md, content/users/fedcloud/faq/_index.md, content/users/fedcloud/openstack/_index.md
=> fix some syntax issues

README.md
Add dependencies installation instructions and how to build
----
#19
=>  Add dependencies installation instructions and how to build

content/users/fedcloud/aod/chipster.md
Update chipster configuration 
----
=> Update chipster configuration

content/en/users/training/_index.md, content/en/users/training/events/_index.md, content/en/users/training/infrastructure/_index.md
Sketch training documentation structure as agreed with @glarocca.
=> Sketch training documentation structure

CODEOWNERS
Introduce code owners, fix #35
=> Introduce code owners, fix #35

content/en/users/fedcloud/federation/_index.md
Fix the name of the referenced field as in https://github.com/EGI-Foundation/fedcloud-documentation/pull/29/files
----
**Related issue :** N/A
=> Terminology fix

CODEOWNERS
Update code owners configuration to avoid being blocked when someone is away.
=> Update code owners configuration

content/en/users/datatransfer/WebFTS/_index.md, content/en/users/datatransfer/api/_index.md, content/en/users/datatransfer/clients/_index.md, content/en/users/datatransfer/monitoring/_index.md
Switch to sh for syntax highlighting, reorder sub-menu items
----
=> Switch to sh for syntax highlighting, reorder sub-menu items

CONTRIBUTING.md
Add some pointers to ease starting with GItHub/Git.
If anyone is having some doc suggestions for people new to git and github it would be good to include it.
=> CONTRIBUTING: add some pointers to ease starting with GItHub/Git

content/en/providers/fedcloud/openstack/_index.md, content/en/users/fedcloud/_index.md, content/en/users/fedcloud/aod/aod.md, content/en/users/fedcloud/aod/chipster.md, content/en/users/fedcloud/auth/_index.md, content/en/users/fedcloud/ec3/basics.md, content/en/users/fedcloud/ec3/ecas.md, content/en/users/fedcloud/faq/_index.md, content/en/users/fedcloud/openstack/_index.md, content/en/users/fedcloud/storage/_index.md, content/en/users/fedcloud/vmi/_index.md, content/en/users/fedcloud/vmops/_index.md
=> Changes from Ville's review of cloud documentation

content/en/users/datatransfer/_index.md, content/en/users/datatransfer/clients/_index.md
Update data-transfer documentation after internal review from Ville
----
=> Update data-transfer documentation after internal review from Ville

content/en/users/notebooks/data/_index.md, content/en/users/notebooks/integration/_index.md, content/en/users/notebooks/training/_index.md
Update of notebooks documentation with latest features 
----
**Related issue :** N/A
=> Review of notebooks documentation

content/en/about/git/_index.md
Document running and testing site.
=> Document running and testing site.

content/en/about/git/_index.md
=> Small fixes, unmix git and gh

content/en/users/notebooks/_index.md, content/en/users/notebooks/data/_index.md, content/en/users/notebooks/faq/_index.md, content/en/users/notebooks/training/_index.md
Review from Gianni as detailed in JIRA 
----
=> Notebooks review from Gianni

.github/workflows/markdown-link-check.yml, .github/workflows/superlinter.yml, .mlc_config.json, .travis.yml
markdown-link-check: Ignore some private URLs related to Check-in
=> markdown-link-check: Ignore some private URLs related to Check-in

.github/workflows/build.yml, .github/workflows/check-links.yml, .github/workflows/lint.yml
actions: no more run tests when commits are pushed to master, only build and deploy
=> actions: no more run tests when commits are pushed to master, only build and deploy

README.md
README: drop travis badge, add some actions badges.
=> README: drop travis badge, add some actions badges.

mlc_config.json
markdown-link-check: ignore some more check-in links
=> markdown-link-check: ignore some more check-in

README.md
Drop references to Travis, reorganise sections.
=> Drop references to Travis, reorganise sections.

content/en/users/cloud-compute/faq/_index.md
Run prettier on the file too
---
=> Add some more OCCI information

content/en/providers/getting-support/_index.md, content/en/support/_index.md, content/en/users/getting-support/_index.md
Only use the main support section, suggesting to use Helpdesk for sevice-specific support and having support email being available.
=> Only use the main support section

content/en/providers/check-in/idp/_index.md, content/en/providers/check-in/sp/_index.md, content/en/users/check-in/faq/_index.md, content/en/users/check-in/vos/_index.md, content/en/users/check-in/vos/voms/_index.md
This PR contains the following changes:
- Add new line before and after "markdownlint" tag
- Remove "mailto" link
- Remove forgotten bracket in entitlement syntax
- Remove unnecessary indent
- Continue numbering in numbered lists
- Use production endpoints in examples
=> Format Check-in files vol.2

content/en/users/cloud-compute/storage/_index.md
Describe how to expose storage with GridFTP for FTS
---
=> Add some FTS info

content/en/providers/check-in/sp/_index.md
Update links in References section of Check-in SP guide
=> [Ckeck-in] Update References in SP guide

content/en/users/cloud-compute/ec3/developers/_index.md
=> Added instructions for EC3 developers

.github/workflows/deploy.yml
=> Use an app token

content/en/providers/cloud-compute/openstack/_index.md
Add the information about outgoing ports
---
=> Add information about outgoing ports

content/en/users/cloud-compute/dynamic-dns/_index.md
=> Fixing small mistyping

content/en/users/cloud-compute/faq/_index.md
Describe how users can release resources without losing their work. Related to EGIREQ-44
---
=> Add one entry on releasing resources

content/en/providers/cloud-compute/openstack/_index.md
=> Improve OpenStack integration documentation

content/en/users/workload-manager/_index.md
=> Added list of VOs supported by the service

content/en/about/contributing/style/_index.md
=> Clarify usage of lists

content/en/providers/check-in/sp/_index.md
Quick fix for the heading size of the previous [PR#206](https://github.com/EGI-Federation/documentation/pull/206)
=> [Check-in] Fix heading size in guide for SPs

content/en/users/datahub/clients/_index.md
=> update onedata version

content/en/providers/datahub/oneprovider/_index.md
=> Added Network Requirements for OneProvider

content/en/users/datahub/clients/_index.md
=> fix reference to old version of the onedata oneclient

.github/workflows/check-links.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, README.md, config.toml, content/en/about/contributing/_index.md, content/en/about/contributing/git/_index.md, content/en/about/contributing/style/_index.md
Rename main to master, update references in workflows and conf.
=> Rename main to master

content/en/users/cloud-compute/openstack/_index.md, content/en/users/notebooks/data/_index.md
Replace 1GB with 10GB in the documentation about persistent storage for notebooks.
---
**Related issue :** https://github.com/EGI-Federation/documentation/issues/213
=> Minor amedments in docs

content/en/users/_index.md, content/en/users/cloud-compute/auth/_index.md
As of version 6.0 of the Operations Portal the list of VOs is browsable without authentication.
This PR just updates the existing link in the docs with the new one.
---
=> Update link to VO list in Operations Portal

content/en/users/cloud-compute/openstack/_index.md
=> Fix missing whitespace

.github/workflows/lint.yml
Slim version do not include rust, dotenv, armttk and pwsh: https://github.com/github/super-linter#slim-image
=> lint: upgrade to slim-v4

content/en/users/cloud-container-compute/k8s.md
Fixes https://github.com/EGI-Federation/documentation/issues/231
=> Update links on k8s docs

content/en/providers/check-in/sp/_index.md
Refactor EGI Check-in documentation for Service Providers. Updated capabilities information for authenticated users section.
=> Egi checkin capabilities fix

content/en/about/contributing/git/_index.md
Update examples to updates modules after having checked out a PR
=> Updates modules after having checked out a PR

README.md, content/en/about/contributing/git/_index.md, package.json
Please see discussion in https://github.com/EGI-Federation/documentation/issues/237
---
Fixes https://github.com/EGI-Federation/documentation/issues/237
=> Harmonize repository setup

assets/scss/_variables_project.scss
After the poll in #documentation, increasing font size from .65rem to .8rem (the old documentation had 1rem font size).
**Related issue :** #249
=> Increase font size, closes #249

content/en/providers/cloud-compute/_index.md
=> Few typos corrected

content/en/users/check-in/vos/_index.md
Expiration policy guidelines for AAI Check-in Registry VO membership lifecycle
=> Expiration policy guidelines for Check-in

content/en/users/workload-manager/_index.md
Some fixes - CYFRONET removed as supplier
---
=> Some fixes

content/en/users/high-throughput-compute/_index.md
Added What is it? summary
Reworded content to make it succinct and easy to read
Corrected typos
Corrected dangling link to VMOPS
=> Revised HTC user documentation

content/en/about/concepts/_index.md
=> Fixed typos in section About

content/en/users/cloud-compute/ec3/_index.md, content/en/users/cloud-compute/gpgpu/_index.md, content/en/users/cloud-compute/im/_index.md, content/en/users/cloud-compute/vmops/_index.md, content/en/users/cloud-container-compute/_index.md, content/en/users/datahub/_index.md, content/en/users/datahub/links/_index.md
Add indico and youtube links to:
* https://docs.egi.eu/users/cloud-compute/vmops/
* https://docs.egi.eu/users/cloud-compute/gpgpu/
* https://docs.egi.eu/users/cloud-compute/im/
* https://docs.egi.eu/users/cloud-compute/ec3/
* https://docs.egi.eu/users/datahub/
---
=> Add indico and youtube links

content/en/users/cloud-compute/gpgpu/_index.md
Update info for IISAS-FedCloud regarding GPU offerings in
https://docs.egi.eu/users/cloud-compute/gpgpu/
@tdviet please review
---
=> Update info for IISAS-FedCloud regarding GPU offerings 

content/en/support/_index.md
Minor rephrasing and better emphasis on what the service is.
---
=> Updated Support section

content/en/internal/_index.md
=> Update wording on Internal Services intro page to match User Guides section

.github/workflows/preview_pr.yml, config.toml
Let people know that the preview is available
---
=> Add some comment to the PR

content/en/users/notebooks/_index.md
Adjusted default resource allocation of the notebooks 
---
No issue created for this
=> updating resources per user and adding link to notebooks

.github/workflows/build_pr_preview.yml, .github/workflows/deploy.yml, .github/workflows/deploy_pr_preview.yml
It seems the workflow still runs on forks, try to not run any deploy step for forks.
Look at fixing the deploy preview workflow that is not run.
=> Fix triggering of preview deploy workflow, do not run any deploy preview step for forks.

.github/workflows/deploy_pr_preview.yml
=> Modify PR preview directory

content/en/providers/operations-manuals/_index.md, content/en/providers/operations-manuals/howto01_site_certification_required_information/_index.md, content/en/providers/operations-manuals/howto02_site_certification_required_documentation/_index.md, content/en/providers/operations-manuals/howto03_site_certificatoin_giis_check/_index.md, content/en/providers/operations-manuals/howto04_site_certification_manual_tests/_index.md, content/en/providers/operations-manuals/man01_how_to_publish_site_information/_index.md, content/en/providers/operations-manuals/man02_service_intervention_management/_index.md
> Work in progress
* Import manual 02: https://wiki.egi.eu/wiki/MAN02_Service_intervention_management
* Import howto 01: https://wiki.egi.eu/wiki/HOWTO01
* Import howto 02: https://wiki.egi.eu/wiki/HOWTO02
* Import how to 03: https://wiki.egi.eu/wiki/HOWTO03
* Import how to 04: https://wiki.egi.eu/wiki/HOWTO04
=> Import manual 02 and how to listed at https://docs.egi.eu/providers/operations-manuals/

content/en/users/getting-started/cli/_index.md, content/en/users/getting-started/openstack/_index.md
Stuff that got through the last few reviews
---
=> Typos and minor fixes

content/en/providers/cloud-compute/configuration/_index.md, content/en/providers/cloud-compute/openstack/_index.md
Fix some of the issues found by sites during integration. 
Also deal with #260
﻿- Use production Check-in
- Add mapping.json info
- Fix file name
---
**Related issue :** #260
=> integration fixes

.github/workflows/check-links.yml, .github/workflows/lint.yml, content/en/users/cloud-compute/gpgpu/_index.md
Thanks to @tdviet for sending the new command in today's Fedcloud Task Force meeting.
As discussed in https://github.com/EGI-Federation/documentation/pull/316#issuecomment-914414114 let's see what happens to line length.
=> Update fedcloudclient command for the discovery of GPUs

CODEOWNERS
@thebe14 adding you to the code owners, so that you could be automatically asked to review PR, we think your input would be valuable during the reviews.
The exact code review assignation can be adjusted as needed/relevant.
=> Add @thebe14 to the code owners

content/en/users/getting-started/cli/_index.md, content/en/users/notebooks/integration/_index.md
Document the option to run `fedcloud` client from EGI Notebooks.
---
=> Connect fedcloudclient with EGI Notebooks

content/en/providers/getting-started/_index.md
=> Minor indentation issue in the ops getting started guide

content/en/providers/cloud-compute/opennebula/_index.md, content/en/providers/cloud-compute/registration/_index.md, content/en/providers/cloud-compute/validation/_index.md, content/en/providers/operations-manuals/man01_how_to_publish_site_information/_index.md, content/en/users/check-in/vos/voms/_index.md, content/en/users/getting-started/architecture/_index.md, content/en/users/workload-manager/_index.md
=> Update link to PROC09

content/en/internal/_index.md, content/en/internal/accounting/_index.md, content/en/internal/configuration-database/_index.md, content/en/internal/getting-started/_index.md, content/en/internal/guidelines-software-development/_index.md, content/en/internal/helpdesk/_index.md, content/en/internal/monitoring/_index.md
Guidelines for software development, taken from the EGI Strategic Innovation Fund (SIF), to be referenced in other documentation.
=> Guidelines for software development

content/en/users/applications-on-demand/_index.md
=> Update ack for vo.access.egi.eu

content/en/providers/cloud-compute/openstack/cloud-info.md
=> Fix the header level

assets/scss/_variables_project.scss, content/en/_index.md, content/en/providers/_index.md, content/en/users/_index.md, layouts/partials/footer.html, layouts/shortcodes/blocks/landing.html, layouts/shortcodes/blocks/section.html, static/css/egi.css
Made changes to the landing page according to this document https://docs.google.com/document/d/1Xq0eLBJU3VR677p8wjl2HMLY2yNDT8J1IgsJQhqhSH8/edit
=> Updated landing page

content/en/users/check-in/joining-virtual-organisation/_index.md, content/en/users/check-in/signup/_index.md
=> Add next steps after signing up in Check-in

content/en/users/cloud-compute/ec3/apps/_index.md
Update OSCAR information in EC3 docs
=> Update OSCAR information in EC3 docs

content/en/users/cloud-compute/gpgpu/_index.md
The `acc-comp.egi.eu` VO was decommissioned and the docs need updating.
This PR updates the relevant page.
---
=> Update GPU docs

content/en/users/tutorials/create-your-first-virtual-machine/_index.md
Update VM tutorial with link to AppDB.
---
=> Update VM tutorial with link to AppDB

content/en/users/online-storage/object-storage/_index.md
Update S3 documentation to remove reference to access via S3 the IFCA endpoint, and the creation of the EC2 access keys
---
=> Update s3 documentation

content/en/users/cloud-compute/openstack/_index.md
=> Update terraform section

content/en/users/check-in/vos/_index.md
This PR introduces the LDAP instructions for VO managers. 
---
**Related issue :**  https://jira.egi.eu/browse/IMSCHM-110
=> Add LDAP instructions for VO managers

content/en/users/notebooks/_index.md
Bring back some text that was removed in one previous PR
---
=> Bring back the VOs to the docs

content/en/providers/cloud-compute/openstack/aai.md
=> Fix fedcloud.egi.eu entitlements

content/en/providers/operations-manuals/_index.md, content/en/providers/operations-manuals/howto01_using_igtf_ca_distribution/_index.md
Import https://wiki.egi.eu/wiki/EGI_IGTF_Release as "HOWTO01 Using IGTF CA distribution"
=> Import https://wiki.egi.eu/wiki/EGI_IGTF_Release as HOWTO01

content/en/providers/cloud-compute/openstack/aai.md
This PR is related to the previous PR [Update client registration in EGI Check-in](https://github.com/EGI-Federation/documentation/pull/372) and modifies a paragraph that was missed out.
=> Update process for registering OIDC clients 2

content/en/internal/messaging/_index.md, content/en/providers/cloud-compute/openstack/_index.md, content/en/providers/cloud-compute/openstack/cloud-info.md
Update messaging documnentation URL as requested by ARGO team, have other pages redirect to internal page on Messaging service.
=> Update messaging documenation URL

content/en/users/high-throughput-compute/_index.md
=> Changed to new HTCondor-CE home page

content/en/users/cloud-compute/openstack/_index.md
Typo and cosmetics for OpenStack docs
=> Typo and cosmetics for OpenStack docs

content/en/internal/helpdesk/features/_index.md, content/en/internal/helpdesk/features/issue-type-values/_index.md
…content/en/internal/helpdesk/features/issue-type-values/_index.md
moving this page https://wiki.egi.eu/wiki/GGUS-IssueType-Values
new PR created since the one made by Renato had some issues. So I copied the file created by him.
---
=> creation of Issue type page

.github/linters/mlc_config.json, content/en/internal/helpdesk/support-staff-guide/_index.md
updating list of ticket categories in the helpdesk support staff guide
---
=> list of ticket categories

content/en/users/datahub/clients/_index.md, content/en/users/tutorials/vm-datahub/_index.md
=> add first tutorial on DataHub

content/en/users/data/storage/block-storage/_index.md
translated from https://grand-est.fr/support-utilisateurs/documentation-en-ligne/guide-dutilisation-dopenstack/#disk-encryption 
---
=> Add section on block storage encryption

content/en/providers/check-in/sp/_index.md
This PR adds the description of `ORCID iD` attribute
=> Add description for `ORCID iD`

.github/linters/mlc_config.json, content/en/users/aai/check-in/vos/_index.md
=> VO membership API v2

AUTHORS, README.md
Update authors file.
Use GitHub account when no email is provided.
=> Update authors file.

content/en/users/compute/orchestration/im/_index.md, content/en/users/compute/orchestration/im/cli/_index.md
Ths PR improve the IM docs adding some TOSCA information.
---
=> Improve IM docs

content/en/users/aai/check-in/vos/_index.md
- Add instructions on how VO Managers can request REST API credentials
=> Improve_egi_check_in_api_v2_instructions

content/en/providers/datahub/oneprovider/_index.md, content/en/users/tutorials/vm-datahub/_index.md
=> Datahub: update OSs supported on tutorial page  and add warning for memcached port

content/en/users/data/management/rucio/admin/_index.md
Fix typo in in the `linkTitle` for https://docs.egi.eu/users/data/management/rucio/admin/
---
=> Rucio administration typo

content/en/users/compute/orchestration/ec3/_index.md
=> Update EC3 link. Fix #436

content/en/users/training/_index.md
As requested by @glarocca I am updating `Training` with `Training Infrastructure` on the left-side menu of the page.
---
=> Update linkTitle for Training Infrastructure

.github/linters/mlc_config.json, content/en/providers/check-in/sp/_index.md
This PR introduces the following changes:
- Add Migration guide to Keycloak and update the development environment endpoints for OIDC
- Add exception for Keycloak URLs to the configuration of Markdown Link Check action
=> [Check-in] Add 'Client Migration to Keycloak' section

content/en/users/data/management/datahub/api/_index.md
=> Add missing eduperson_entitlement in scope

content/en/providers/check-in/idp/_index.md, content/en/providers/check-in/sp/_index.md, content/en/providers/cloud-compute/openstack/aai.md
This PR introduces the following changes:
- Break `Endpoints` table per environment using tabpanex
- Add section for the intrspection endpoint in migration guide
- Add "Common Issues" section
- Add sub-sections in `Client Migration to Keycloak`
- Update endpoints with the Keycloak OIDC Endpoints in OpenStack guide
=> Improve `Client Migration to Keycloak` instructions

content/en/users/compute/cloud-compute/dynamic-dns/_index.md
Adding demo video in YouTube and support via GGUS to the documentation.
=> Updating docs for Dynamic DNS

content/en/internal/helpdesk/features/ticket-priority/_index.md
fixed the table in "Algorithm for middleware related tickets" section
=> fixed the formatting of a table

content/en/providers/check-in/sp/_index.md, content/en/users/aai/check-in/obtaining-tokens/oidc-agent/_index.md
This PR introduces the following changes:
- Update decommission deadline of the Production instance of Check-in
- Add instructions for oidc-agent
=> [Check-in] Add instructions for obtaining tokens using oidc-agent

content/en/providers/cloud-compute/openstack/aai.md
Try to warn admis about issues found at several sites
---
=> Add a warning about the config of Require claim

content/en/about/contributing/git/_index.md, content/en/users/compute/content-distribution/_index.md, content/en/users/data/storage/grid-storage/_index.md, content/en/users/tutorials/data-transfer-object-storage/_index.md
=> Add link to EOS in grid storage section

content/en/providers/cloud-compute/openstack/aai.md
Tackles [comment](https://github.com/EGI-Federation/documentation/commit/619999870000c8dc87bf2dd71c2ea52d7b82228c#commitcomment-80596800). Adds the command to apply the 
mappings once the file has been updates
---
=> Remind to apply mappings

content/en/internal/configuration-database/users-roles/managing-accounts/_index.md
This PR updates the managing-accounts documentation, mostly around identity linking within GOCDB, which is a new feature as of GOCDB 5.9.0
=> internal/configuration-database: Update managing-accounts documentation

content/en/providers/operations-manuals/faq-hepspec06/_index.md, content/en/providers/operations-manuals/howto03_site_certificatoin_giis_check/_index.md
moving https://wiki.egi.eu/wiki/FAQ_HEP_SPEC06 to new place
=> FAQ hepspec06 page creation

content/en/internal/configuration-database/service-types/_index.md, content/en/users/data/storage/object-storage/_index.md
=> Adding more S3 clients examples to the docs

content/en/providers/getting-started/joining/federated-resource-centre/_index.md
updated the section about SLAs and OLAs; removed the section about managing service orders.
=> content updated

content/en/internal/guidelines-software-development/_index.md
Reference Introduction to Software Security (video course by Trusted CI, WISC, UAB)
=> Reference Introduction to Software Security (video course)

content/en/users/compute/cloud-compute/faq/_index.md
Addresses the comments in https://github.com/EGI-Federation/documentation/issues/496
---
**Related issue :** https://github.com/EGI-Federation/documentation/issues/496
=> How to list all owned VMs in fedcloud

content/en/internal/configuration-database/access/_index.md, content/en/internal/configuration-database/users-roles/managing-accounts/_index.md
configuration database: document account registration/access fix.
Migrated and integrated from:
* https://wiki.egi.eu/wiki/GOCDB/Input_System_User_Documentation#Registering_a_new_user_account
* https://wiki.egi.eu/wiki/GOCDB/Input_System_User_Documentation#Changing_your_accountID
=> configuration database: document account registration/access fix

content/en/internal/_index.md, content/en/internal/helpdesk/account-and-privileges/_index.md, content/en/internal/monitoring/_index.md, content/en/internal/monitoring/service-information/_index.md, content/en/internal/operations-portal/service-information/_index.md, content/en/providers/joining/core-service/_index.md, content/en/providers/joining/federated-resource-centre/_index.md, content/en/providers/joining/new-provider/_index.md, content/en/providers/joining/technology-provider/_index.md, content/en/users/_index.md, content/en/users/data/management/rucio/admin/_index.md, content/en/users/data/management/rucio/getting-started/_index.md, content/en/users/dev-env/binder/_index.md, content/en/users/dev-env/notebooks/_index.md, content/en/users/dev-env/notebooks/kernels/matlab/_index.md, content/en/users/getting-started/_index.md, content/en/users/getting-started/architecture/_index.md, content/en/users/getting-started/cli/_index.md
A couple of links in https://docs.egi.eu/providers/joining/federated-resource-centre/ need updating.
---
=> Update links under users, providers and internal sections

content/en/users/compute/cloud-container-compute/docker/_index.md
=> known issue: MTU in docker

content/en/about/contributing/style/_index.md, content/en/internal/configuration-database/_index.md, content/en/internal/configuration-database/adding-service-endpoint/_index.md, content/en/internal/configuration-database/ngi-core-services/_index.md, content/en/providers/check-in/sp/_index.md, content/en/providers/cloud-compute/openstack/accounting.md, content/en/providers/operations-manuals/man06_failover_for_mysql_grid_based_services/_index.md, content/en/users/aai/check-in/vos/voms/_index.md, content/en/users/compute/orchestration/ec3/_index.md, content/en/users/data/management/datahub/_index.md, content/en/users/data/storage/block-storage/_index.md, content/en/users/dev-env/notebooks/training/_index.md
from https://wiki.egi.eu/w/index.php?title=NGI_services_in_GOCDB&oldid=112084
removed the links to that page
=> updating the list of required services

.github/linters/mlc_config.json
link check: ignore URL protected by Check-in
=> link check: ignore URL protected by Check-in

.github/linters/mlc_config.json
Disable markdownling check for ops portal URL protected by Check-in
=> Disable markdownling check for ops portal URL protected by Check-in

.github/workflows/deploy_pr_preview.yml
Fix wrong up to GET_OUTPUT introduced in #526.
=> Fix wrong up to GET_OUTPUT introduced in #526

content/en/users/dev-env/notebooks/data/_index.md
Removed fsonedata-fs as it's not installed by default and added info about notebooks-shared  space
---
=> Update docs about the FIle Management in notebooks

content/en/providers/notebooks/operations/_index.md
=> update repo for notebooks operations

content/en/users/compute/orchestration/workload-manager/_index.md
=> Replace EGI with EOSC marketplace for DIRAC

content/en/users/data/management/data-transfer/_index.md
=> update UKRI-STFC FTS endpoints

content/en/users/data/management/datahub/usecases/_index.md
=> Update DataHub use cases description

content/en/users/compute/cloud-compute/auth/_index.md
Add documentation about ssh-oidc
=> Ssh OIDC marcus

content/en/users/compute/cloud-compute/sites/_index.md, content/en/users/compute/cloud-container-compute/docker/_index.md, content/en/users/service-providers/_index.md
=> Add site-specific docs

content/en/users/data/management/rucio/_index.md
This PR brings some requirements that users should consider when choosing Rucio as their data management solution
as well as a couple of usecases that users may use Rucio for.
=> Adding usecases and requirements to Rucio

content/en/users/aai/check-in/vos/_index.md
Improve Check-in REST API documentation
=> checkin_rest_api_documentation_improvements

content/en/users/getting-started/_index.md
=> Add default capacity allocation back

.github/PULL_REQUEST_TEMPLATE.md
Mention PR description will be used as the commit message.
=> Mention PR description will be the commit message

content/en/about/contributing/git/_index.md
Document running tests locally, leveraging docker.
act can be used too but may be be longer or more complex, to be tested more.
=> Document running tests locally. Fix #468.

content/en/users/getting-started/architecture/_index.md
=> Deal with #590

content/en/users/dev-env/notebooks/_index.md, content/en/users/dev-env/replay/_index.md
Update details in Notebooks and Replay (Binder) service:
* resource limits
* enabled VOs
=> Update resources limits and supported VOs for Notebooks

content/en/internal/helpdesk/features/report-generator/_index.md, content/en/internal/helpdesk/features/ticket-scope/_index.md
Moved from https://wiki.egi.eu/wiki/GGUS-Ticket-Scope
=> helpdesk: document ticket scope

.github/linters/mlc_config.json, .github/workflows/check-links.yml, content/en/internal/security-coordination/_index.md, content/en/providers/cloud-compute/openstack/aai.md, content/en/providers/cloud-compute/openstack/cloud-info.md, content/en/providers/joining/federated-resource-centre/_index.md, content/en/support/_index.md, content/en/users/compute/cloud-compute/_index.md, content/en/users/compute/high-throughput-compute/_index.md, content/en/users/compute/orchestration/workload-manager/_index.md, content/en/users/data/management/data-transfer/_index.md, content/en/users/data/management/datahub/clients/_index.md, content/en/users/data/management/rucio/admin/_index.md, content/en/users/data/management/rucio/getting-started/_index.md, content/en/users/data/storage/object-storage/_index.md, content/en/users/getting-started/_index.md, content/en/users/getting-started/communities/dmcc/_index.md
- Force checking every link
- Weekly schedule checks for links 
---
**Related issue :** #603
=> Enforce link checking

content/en/users/data/management/datahub/clients/_index.md
=> use latest major release of oneclient

CODEOWNERS
Bring CST members into the user section
---
=> First attempt to fix the owners

content/en/providers/high-throughput-compute/_index.md, content/en/providers/high-throughput-compute/htcondor-ce-accounting/_index.md
This PR updates the description and examples of HTC accounting to include the new HEPScore benchmark.
---
**Related issue :** None
=> Add HEPScore23 to example

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, .github/actions/spelling/patterns.txt
Some more fixes for spelling dictionaries.
=> Fix dictionaries

content/en/internal/helpdesk/account-and-privileges/_index.md
Updated screenshot on registration info; replaced "persistent ID" by "VOPersonID"
---
=> Updated documentation on GGUS account and privileges; Update _index.md

content/en/users/getting-started/communities/dmcc/_index.md
xref: https://github.com/EGI-Federation/documentation/pull/611
=> Remove Rucio section for DMCC community

content/en/providers/cloud-compute/openstack/vo-config/_index.md
Be more precise on the role needed for cASO
---
=> Fine tune the role for cASO

.github/actions/spelling/allow.txt, .github/actions/spelling/patterns.txt, content/en/users/compute/cloud-compute/gpgpu/_index.md, content/en/users/getting-started/_index.md, content/en/users/getting-started/architecture/_index.md, content/en/users/tutorials/adhoc/create-your-first-virtual-machine/_index.md
Point end users to supported deployment tools.
---
=> Remove references to deprecated services

content/en/users/dev-env/notebooks/_index.md
Make sure the numbers are consistent everywhere
(Should this be just places in a single place?)
---
=> Keep adjusting the quota everywhere

content/en/users/getting-started/_index.md
Update quota of cloud `*` compute services
---
=> Update quota for cloud compute services

.github/actions/spelling/allow.txt, content/en/providers/joining/federated-resource-centre/_index.md, content/en/users/compute/orchestration/workload-manager/_index.md, content/en/users/getting-started/communities/pangeo/_index.md
The [EOSC Portal](https://eosc-portal.eu/about) redirects now to the [EOSC EU Node](https://open-science-cloud.ec.europa.eu/).
The [EOSC Marketplace](https://marketplace.eosc-portal.eu/) is no longer available.
This PR updates the references to both.
---
=> Replace references to https://eosc-portal.eu/

content/en/internal/helpdesk/features/team-tickets/_index.md
A trivial white-space formatting fix
=> Formatting fix

content/en/users/compute/orchestration/im/dashboard/_index.md
Explicit URL to EGI IM Dashboard
In IM Dashboard (index) doc page, the reference to IM Dashboard is done through a hidden, under-the-text link (i.e, [IM Dashboard](https://im.egi.eu)). For accessibility reasons and better communication, important links should be explicit. This is what this PR does: explicit IM Dashboard address (`https://im.egi.eu`)
---
No related issues.
=> Explicit IM Dashboard URL

content/en/users/compute/software-distribution/_index.md
---
**Related issue :** https://ggus.eu/?mode=ticket_info&ticket_id=168616
=> add link to documentation for the client setup

.github/actions/spelling/expect.txt, .github/actions/spelling/patterns.txt, content/en/users/tutorials/advanced/_index.md, content/en/users/tutorials/intermediate/_index.md, content/en/users/tutorials/scientific/_index.md
Update tutorials with the latest ones from https://www.egi.eu/trainings-and-webinars/
---
=> Tutorial updates

.github/actions/spelling/allow.txt, content/en/internal/helpdesk/features/ticket-priority/_index.md
=> Update ticket priority page

content/en/users/dev-env/notebooks/_index.md
=> Update enrollment URL for the Notebooks VO

.github/actions/spelling/expect.txt, content/en/users/aai/check-in/faq/_index.md
Using https://helpdesk.ggus.eu/ instead of https://ggus.eu/
---
=> Update GGUS link

.github/workflows/deploy_pr_preview.yml, .github/workflows/link-health-check.yml
=> test(links): use explicit path to local cached tools

content/en/providers/cloud-compute/openstack/accounting/_index.md
Remove appliance references and just point to upstream repos
---
=> Remove references to appliance

content/en/users/aai/check-in/signup/_index.md
As discussed internally, the link https://aai.egi.eu/signup is better for the signup process
=> Update Check-in sign up link

content/en/users/compute/cloud-compute/images/_index.md
Move up the upload of images and include information on how to request projects.
---
=> feat(cloud-compute): improve the image management

.github/actions/spelling/allow.txt, content/en/users/training/_index.md
Update training infrastructure page with updated information.
---
=> Update training infrastructure page
